### ISSUE TITLE
Rainbow Furnace/Linker Issues + Crash

### ISSUE THREAD

**Issue by Tankenheimer** [Qelifern/IronFurnaces#102]
### Forge Version

40.1.20

### Iron Furnaces Version

1.18.2-3.3.0

### Describe your issue

Currently playing on AllTheMods7 0.4.2

Shift + right-click on copper, iron, silver, gold, diamond, crystal, emerald, obsidian, glass, and netherite furnaces with the rainbow linker cause the coordinates of the furnace to be displayed twice.

Shift + right-click on a rainbow furnace with the rainbow linker after selecting a furnace to be linked shows the furnace in question being linked twice, and shows two separate numbers of furnaces missing:

"Missing: 7
Added: Iron Furnace
Missing: 9
Added: Iron Furnace"

The rainbow furnace does not seem to output power with either 7 or 9 furnaces linked and all burning simultaneously.

Destroying a furnace saved to the rainbow linker and then shift + right-clicking a rainbow furnace to check its status crashes the game and shows the following error:

"The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "ironfurnaces.tileentity.furnaces.BlockIronFurnaceTileBase.m_58900_()" because "toAdd" is null
Exit Code: -1"

**Comment by Qelifern** [comment]
Was this on a server or singleplayer?

**Comment by Qelifern** [comment]
Unable to reproduce
3.6.3 adds more != null checks that shouldve been in from the start
