### ISSUE TITLE
Modpack Crashing on Launch

### ISSUE THREAD

**Issue by connorx2000** [Qelifern/IronFurnaces#104]
### Forge Version

36.2.34

### Iron Furnaces Version

ironfurnaces-1.16.5-2.7.7.jar

### Describe your issue

When launching the modpack it crashes with Iron Furnaces enabled. If i disable Iron Furnaces everything works fine.

### Crash Report

https://pastebin.com/eVe48PdY

**Comment by connorx2000** [comment]
Update Im pretty sure its Electrodynamics and Iron Furnace conflicting as disabling Electro and Enable Iron Furnaces works.

**Comment by Qelifern** [comment]
1.16.5 is no longer supported
