### ISSUE TITLE
Lava buckets can't be used as a hopper-input fuel

### ISSUE THREAD

**Issue by SantiagoSanMartin** [Qelifern/IronFurnaces#109]
### Forge Version

41.0.63

### Iron Furnaces Version

1.19-3.4.0

### Describe your issue

Now that lava is a renewable resource, my friends and I set a sort of forge room, with cauldrons filling with lava and a simple vanilla furnace mechanism. We put the ores on a chest with hopper on TOP. The output goes through bottom with another hopper and finally the lava buckets are set to the fuel slot from either side with another hopper and chest. This works in vanilla, the lava is consumed, the empty bucket is treated as an output and is returned in the bottom chest, freeing the space for another lava bucket to be inserted from the side.

After adding IronFurnaces, we tried a similar setup, this time using obsidian furnaces. 
But it doesn't work with the lava buckets, the first lava bucket is consumed... but the empty bucket is not removed from the fuel slot, impeding new buckets from being inserted.

Is this something that can be patched to allow the empty buckets to go through the output slot? Or otherwise add some kind of configuration to treat these new furnaces as vanilla furnaces?

**Comment by SantiagoSanMartin** [comment]
A funny parody of our issue, hope it cracks a smile
https://www.youtube.com/watch?v=VjXOwUnJzA0

**Comment by Qelifern** [comment]
Fixed 3.6.1

**Comment by jpterrazam** [comment]
I'm using version 3.6.4 and this issue keeps happening
