### ISSUE TITLE
Blast and Smoker Gold furnace are faster than diamond blast and smoker

### ISSUE THREAD

**Issue by Solarius66** [Qelifern/IronFurnaces#111]
### Forge Version

40.1.60

### Iron Furnaces Version

3.3.1

### Describe your issue

When using the Blasting or Smoking augments on GOLD furnace, it becomes faster than DIAMOND furnace with the same augment.

Tested with wireless heat receiver and Coal blocks, with raw Chicken and copper/iron ore.

**Comment by Qelifern** [comment]
Fixed 3.6.1
