### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by sargeow** [Qelifern/IronFurnaces#112]
### Forge Version

40.1.20

### Iron Furnaces Version

3.2.1

### Describe your issue

crashing server on start-up

### Crash Report

https://gist.github.com/sargeow/9eb1281cc79924502ea87c0315cb87d4

**Comment by sargeow** [comment]
updated alot of stuff since this post still not working on latest forge and latest iron furnace versions.
*Server Log* https://gist.github.com/sargeow/126599a7e014875ebc95a56213a1ab22

**Comment by Qelifern** [comment]
Fixed
