### ISSUE TITLE
1.19 java.lang.reflect.invocationtargetexception error

### ISSUE THREAD

**Issue by Ahley411** [Qelifern/IronFurnaces#115]
### Forge Version

41.0.113

### Iron Furnaces Version

1.19

### Describe your issue

![image](https://user-images.githubusercontent.com/72476191/181133599-5436fa21-33de-4d10-b013-bfba0555e73a.png)

No amount of updating forge versions could pass by this error, same error only on 1.19. Would love to be notified when/if this is fixed.

Email me any further questions about this. Thank you.

### Crash Report

https://docs.google.com/document/d/1e8PpFDR7mfGQfZLzLZstz96jLRw5IAF-6UWGwZhj8WM/edit?usp=sharing

**Comment by Qelifern** [comment]
Fixed
