### ISSUE TITLE
Item vanishes

### ISSUE THREAD

**Issue by Luca99iscool** [Qelifern/IronFurnaces#116]
### Forge Version

40

### Iron Furnaces Version

ironfurnaces-1.18.2-3.3.1

### Describe your issue

When i try to put a item in with a hopper and the furnace as an factory upgrade it Eats the item 
The item comes back when i break the furnace

**Comment by Qelifern** [comment]
Fixed in 3.6.1

**Comment by Xhenos119** [comment]
I have the same issue, would it be safe to update the mod without creating issues with ATM 7 to the sky?
