### ISSUE TITLE
Empty Lava Bucket Dissapears

### ISSUE THREAD

**Issue by chrisgates301** [Qelifern/IronFurnaces#117]
### Forge Version

41.0.1

### Iron Furnaces Version

3.3.1

### Describe your issue

When using lava buckets as fuel for the furnaces, activating the auto imput option, it automatically grabs a new lava bucket when needed, the empty bucket goes back to the container (lets say there is a chest behind the furnace, with lava buckets, the empty bucket goes back there), but, if there is already one or more empty buckets in the container, the following empty buckets that come from the furnace dissapear

**Comment by Qelifern** [comment]
Fixed in 3.6.1
