### ISSUE TITLE
IronFurnaces wont fill up drawers and Items get deleted.

### ISSUE THREAD

**Issue by Puddel** [Qelifern/IronFurnaces#119]
### Forge Version

40.1.68

### Iron Furnaces Version

ironfurnaces-1.18.2-3.3.1.jar

### Describe your issue

IronFurnaces can only extract 64 Items into a Storage Drawer even though it has not reached its maximum capacity. When a void upgrade is used on the Drawer the items will get deleted.
![image](https://user-images.githubusercontent.com/37541868/185234738-eba8cf08-7239-47a9-846c-27e448b42f50.png)
![image](https://user-images.githubusercontent.com/37541868/185234924-45a43759-7864-498f-aaca-8d7037d97a19.png)

Items also get deleted when the IronFurnaces try to output their items into an emtpy and locked Drawer.
![image](https://user-images.githubusercontent.com/37541868/185235560-2114c28a-5ea1-4fa8-b5e9-72c827a90c75.png)
![image](https://user-images.githubusercontent.com/37541868/185235615-a8fdd1e8-cd74-473c-b862-42fca69d7214.png)

P.S.: I noticed it in the modpack ATM7 to the Sky
Functional Drawers version: functionalstorage-1.18.2-1.0.2.jar

**Comment by Vanadin1** [comment]
Same issue
Pack ATM 7. Forge 1.18.2
If the output location is full or can't accept it, it just deletes the item.

**Comment by cha0s** [comment]
I've been bitten by this one as well.

Iron furnaces delete items.

**Comment by Vanadin1** [comment]
It seems if the output inventory is an inventory, but is full, Iron furnaces just wipes the item off the face of the planet.

**Comment by Qelifern** [comment]
3.6.3 fixes this
