### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by GeorgeTDFgoat** [Qelifern/IronFurnaces#120]
### Forge Version

41.1.0

### Iron Furnaces Version

ironfurnaces-1.19-3.4.0.jar

### Describe your issue

![image](https://user-images.githubusercontent.com/111645791/185751123-50d79aca-c444-4400-93dd-12cd98f727f7.png)

**Comment by JustRed23** [comment]
An InvocationTargetException usually leads to a mixin inject error, meaning that a mod couldnt find a specific function or object in the code to use. This could be caused by other mods patching that function like performance mods.

**Comment by Qelifern** [comment]
Unable to reproduce
