### ISSUE TITLE
[Suggestion] Add client-side config option to disable light updates

### ISSUE THREAD

**Issue by Nevrai** [Qelifern/IronFurnaces#121]
### Describe your issue

Iron Furnaces can heavily impact your frame rate, especially when using extremely fast modded furnaces like the unobtainium furnace in the [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) modpack (especially with the factory upgrade), which smelts 64 items per tick.

The furnace constantly performs light updates, which not only causes fast visual flickers from the furnace with the fastest furnaces, but worse than that, it also heavily impacts frame rates to the point where the game becomes practically unplayable with a couple of these furnaces running.

It would be _much_ appreciated if you could add a client-side option for simply toggling off light emission and light updates from Iron Furnaces furnaces, causing any furnace not to emit any light and perform no light updates. This would improve frame rates _immensely_ with fast furnaces like the unobtainium furnace from the All the Mods 7 pack and would also improve frame rates in general when using multiple furnaces from this mod. I hope that’s not too much to ask for, and it would be a huge improvement!

I’m playing [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (v0.4.29 [latest]) for Minecraft 1.18.2, on Forge 40.1.68, with version 3.1.1 of Iron Furnaces (latest for 1.18.2).

**Comment by Qelifern** [comment]
3.6.3 adds this feature

**Comment by Nevrai** [comment]
@Qelifern That is great! Is there a chance this feature could be backported to the 1.18.2 version?
