### ISSUE TITLE
Bucket gets deleted upon fuel use

### ISSUE THREAD

**Issue by Adzeiros** [Qelifern/IronFurnaces#122]
### Forge Version

40.1.68

### Iron Furnaces Version

ironfurnaces-1.18.2-3.3.1

### Describe your issue

I am using lava buckets to fuel the Iron furnace...

Generally with auto output off this works as expected and the empty bucket remains in the fuel slot... 

However, I set up a system with some Barrels above and below them in order to auto import and output the items...

I leave an extra filled lava bucket in the fuel slot so it can refuel as needed... However, when I come back after some time to check on it, the furnace's fuel has refilled, but the buckets are gone from the slots and are not in the barrel below it...

Now, since I am using ATM7 and have the create mod, I have an Iron generator so remaking buckets isn't too big of an issue for me. However, it would be nice not to make new buckets each time...

**Comment by Qelifern** [comment]
Unable to reproduce on 1.19.2
