### ISSUE TITLE
getPlayer appears to need network access

### ISSUE THREAD

**Issue by JoshuaRowePhantom** [Qelifern/IronFurnaces#126]
### Forge Version

40.1.74

### Iron Furnaces Version

ironfurnaces-1.18.2-3.3.1

### Describe your issue

Config.getPlayer appears to implement some behavior during world tick that reads a .json file from the web and gives certain players some advantages. This behavior happens during the world tick, and when outbound network connections are not permitted cause the world to be unusable when a 60 second watchdog is applied, as it is in some modpacks.

Perhaps this behvaior should be in a config file instead of a URL download?

**Comment by Qelifern** [comment]
3.6.3 : Config option added to avoid this under the Misc category.
