### ISSUE TITLE
[1.18.2] Factory Augment does not work with pipes

### ISSUE THREAD

**Issue by Kauruck** [Qelifern/IronFurnaces#128]
### Forge Version

40.1.76

### Fabric Version

N/A

### Iron Furnaces Version

1.18.2-3.3.1

### Describe your issue

# Description
When using a furnace together with a form of item transportation from another mod e.g. Mekanism's logistical transporter, items put in for smelting will first fill up internal slot(s) (I have seen 2 stacks) and the excess will be smelted. The items in the hidden slot can only be obtained by breaking the furnace.

# To Reproduce 
Use a logistical transporter to pump one sand (or any other smeltable item) into a furnace with the "Augment: Factory" installed. The item will not be smelted.
When breaking the furnace the item (sand) will drop.

# Mods used
- Iron Furnaces 1.18.2-3.3.1 
- Mekanism 10.2.5

### Crash Report

N/A

**Comment by SIowie** [comment]
The so called "hidden slots" are the ones that are available after upgrading the furnace to a better version that has more than 1/2 slots available for smelting
![image](https://user-images.githubusercontent.com/41696977/189236895-8280da75-3332-482e-86c7-0d8c4f41e207.png)
It pushes the items into unavailable slots that the furnance cant smelt, which makes them unusable until you upgrade/destroy the furnace.

**Comment by jcwillox** [comment]
I've noticed this bug with `refinedstorage-1.10.3` crafters as well. For anyone looking for a workaround, it appears that depositing into an attached inventory like a barrel and using the auto input function on the factory avoids this bug.

**Comment by Halogen3047** [comment]
Also had this issue with a Mekanism Enrichment Chamber set to auto eject into gold furnace with factory upgrade.
Seems to work when I have auto eject off on the Enrichment Chamber and auto input ON on the gold furnace.

**Comment by Quazaka** [comment]
I am having the same issue when using AE. 
As seen on these images, there are items hidden away in the unavaible slots. 
![MNg1S1f](https://user-images.githubusercontent.com/6616239/192272412-6cddbe0f-7815-4aa5-8b7f-801933f715ea.png)
![ovWpEm1](https://user-images.githubusercontent.com/6616239/192272474-64c752b2-099a-40ed-b764-be4528be1a7b.png)

**Comment by Qelifern** [comment]
Fixed in 3.6.1

**Comment by xannor** [comment]
This issue was posted for 1.18.2 (Probably ATM To The sky, which is what I am playing) but on curse forge it looks like you only released this for 1.19.x. Do you plan on backporting this to the 1.18.2 releases or is this going to be a forever "known" issue in 1.18.2 modpacks?
