### ISSUE TITLE
ATM Furnaces do not allow for multiple outputs per piece smelted

### ISSUE THREAD

**Issue by djnifos** [Qelifern/IronFurnaces#132]
### Forge Version

43.1.43

### Iron Furnaces Version

3.6.3

### Describe your issue

When smelting Deep Resonance resonating ore in any of the base furnaces (tested up to netherite) the result is 8 plates per smelted ore.  The ATM furnaces smelt 16/32/64 at a time, only resulting in 16/32/64 plates, instead of 8x that amount as expected.

Not sure how that would be handled any differently as even the base ATM furnace would be 2 full stacks, but someone complained in #ATM8-help in the ATM discord, and I thought I'd share it here.

**Comment by Qelifern** [comment]
Thanks for your report, this has gone overlooked and will be fixed in the next update.
