### ISSUE TITLE
Using Furnace Linker on Vanilla Furnace throws unhandled exception

### ISSUE THREAD

**Issue by yxji** [Qelifern/IronFurnaces#135]
### Forge Version

40.1.76

### Iron Furnaces Version

3.3.1

### Describe your issue

Used Furnace Linker (Shift+Right-Click) on vanilla Minecraft furnace. Caused game to stop responding (2657ms/53 ticks behind) before crashing and closing completely.

Code threw an unhandled exception due to not being able to cast the entity properly.
java.lang.ClassCastException: class net.minecraft.world.level.block.entity.FurnaceBlockEntity cannot be cast to class ironfurnaces.tileentity.furnaces.BlockIronFurnaceTileBase 

**Other info**

**ModPack:**  Skyopolis 5
**Mode:**   Single-player, Local server

### Crash Report

https://gist.github.com/yxji/3763b1109239cebe51d730c306d35fda

**Comment by yxji** [comment]
Hello Iron Furnaces Team! Looking at the ItemLinker.java code I expect the issue to be resolved in the 1.19.2 branch (in 3.6.3) but present in earlier versions.

I'm not sure what your preferred process is testing and closing issues like this so I'll leave this issue as open.

Thank you for making an awesome MC mod!

**Comment by Qelifern** [comment]
1.18.2-3.3.2 has the implemented fix, thanks for your report.
