### ISSUE TITLE
Iron Furnace cause lag when experience keep in the furnace

### ISSUE THREAD

**Issue by nickbanana** [Qelifern/IronFurnaces#137]
### Forge Version

40.1.80

### Iron Furnaces Version

1.18.2-3.3.2

### Describe your issue

similar to #58 , but since I'm using factory upgrade, and turning on auto-input/auto-output. It causing serious lag on server side even after finish burning.

For reference, I'm burning a lot of copper (at least 30*64 raw copper) in only one single emerald furnace.

By using Observable mod to profile the furnace, it's using 28952us per tick before take the experience out, and the function which is eating server resource is as same as #58.

After take the experience out (by destroying the furnace), the lag resolved.

Will post the observable image a few hours later

**Comment by Qelifern** [comment]
Next version has changed how the furnace handles XP, will keep this issue open if lag still exists with new version.

**Comment by MagisterXero** [comment]
I've got an update to this.
MC - 1.20.1

You can reproduce this lag by setting up an infinite loop of processing, furnace to crusher for ingots -> dust -> ingot.
Each furnace adds about 1.25~1.5 tps while Auto OUTPUT is turned on.
By adding a mere 30 furnaces in an infinite loop, the TPS already begins to approach the limit where server TPS drops below 20~TPS.

Not sure if it is caused by the experience points, but the spark profiler said it was the autoFactoryIO() function.
Specifically it's the Auto OUTPUT only, as input seems to not reduce TPS much.
![image](https://github.com/Qelifern/IronFurnaces/assets/1440404/6da948b4-a520-40e6-a23e-81645894c93f)

**Comment by Qelifern** [comment]
> I've got an update to this. MC - 1.20.1
> 
> You can reproduce this lag by setting up an infinite loop of processing, furnace to crusher for ingots -> dust -> ingot. Each furnace adds about 1.25~1.5 tps while Auto OUTPUT is turned on. By adding a mere 30 furnaces in an infinite loop, the TPS already begins to approach the limit where server TPS drops below 20~TPS.
> 
> Not sure if it is caused by the experience points, but the spark profiler said it was the autoFactoryIO() function. Specifically it's the Auto OUTPUT only, as input seems to not reduce TPS much. ![image](https://user-images.githubusercontent.com/1440404/274041190-6da948b4-a520-40e6-a23e-81645894c93f.png)

I've spent 2 hours trying to replicate those numbers on the profiler and I have not been successful, can you provide a link to the spark profile?

**Comment by MagisterXero** [comment]
https://spark.lucko.me/yEAm4Sx9H5

**Comment by MagisterXero** [comment]
![image](https://github.com/Qelifern/IronFurnaces/assets/1440404/e5f32c8e-f672-4f09-837e-6b62c4626e48)
![image](https://github.com/Qelifern/IronFurnaces/assets/1440404/303d5ec8-7f83-4058-8a58-cab744e4e865)
Here's the setup I used in SSP.

Bear in mind, the spark profile is from a SMP server. Modpack is TNP LL7

With just these 30 furnaces, I was broaching about a mean time per tick of almost 40ms, which is close to when the 20 TPS begins to drop.

Each barrel has a hopper upgrade in it which is also inserting/pulling, and the EnderIO sagmills are pulling/pushing as well.

**Comment by Qelifern** [comment]
I think the problem is staring me in the face. How I didnt realize getRecipe doesnt consult the CACHE is a mystery hehe.

`protected Optional<AbstractCookingRecipe> getRecipe(ItemStack stack) {
        Optional<AbstractCookingRecipe> recipe = getCache().computeIfAbsent(stack.getItem(), (item) -> (stack.getItem() instanceof AirItem)
                ? Optional.empty()
                : Optional.ofNullable(this.level.getRecipeManager().getRecipeFor((RecipeType<AbstractCookingRecipe>) recipeType, new SimpleContainer(stack), this.level).orElse(null)));
        return recipe;
    }`

Trying something like this and will test it on a modpack this time.

**Comment by Qelifern** [comment]
![b6e2683f94625d2b9c7c36d376528d7a](https://github.com/Qelifern/IronFurnaces/assets/48419229/a2c74884-986d-4eae-8adb-02cb3a584c8e)

This is 6 furnaces smelting gold infinitely on ATM 9 pack. Looks like ItemHandlerHelper.canItemStacksStack is pretty slow. Aside from that nothing jumps out at me.

Here's a link to 4.1.1 if you want to test for yourself.
[https://drive.google.com/file/d/1PwzlutRq5Nq_1j448KtnVjprXqEFAAUt/view?usp=drive_link](url)

**Comment by MagisterXero** [comment]
Seems like it's better it was based on that profiler at least!
Won't have a chance to test until modpacks are updated. 
Is 4.1.1 in release or testing?

**Comment by Qelifern** [comment]
currently testing 4.1.1, will try to get it released today, will be busy all week and I dont want ppl to have furnace lag machines
