### ISSUE TITLE
Wireless Heat Receiver deleted

### ISSUE THREAD

**Issue by AnchorZer0** [Qelifern/IronFurnaces#139]
### Iron Furnaces Version

1.18.2-3.3.1

### Describe your issue

I had an Obsidian Furnace with Augment: Generator and I placed a Wireless Heat Receiver in it and it got deleted. I tried a bound and unbound version of it with the same results. I use this in the Vault Hunters mod and they think that the issue is on your side.

**Comment by Qelifern** [comment]
Sounds like it ate the Heat Receiever to generate power since it has a burntime, this should not happen. Thanks for the report.

**Comment by Qelifern** [comment]
This has been fixed in recent versions.
