### ISSUE TITLE
Smoker texture displays on bottom of furnace when using smoker upgrade

### ISSUE THREAD

**Issue by rckymtnrfc** [Qelifern/IronFurnaces#142]
### Forge Version

43.1.55

### Fabric Version

NA

### Iron Furnaces Version

3.6.4

### Describe your issue

Minor issue but I noticed when using the smoker upgrade the texture for the top of the furnaces is also used for the bottom texture.  I confirmed this on the copper and gold furnaces, assumed it happens on the rest.

**Comment by Qelifern** [comment]
Fixed in 1.19.3-3.7.2
