### ISSUE TITLE
Comparator crashes server

### ISSUE THREAD

**Issue by Batt11** [Qelifern/IronFurnaces#144]
### Forge Version

1.19.2-43.1.55

### Iron Furnaces Version

3.6.4

### Describe your issue

I have a personal ATM8 server that only I play on. I found that if I click on the Comparator buttons in any furnace, I crash my server. I am able to restart the server, but when I try to log in again, it crashes again. I had to pull a backup to be able to log in again. 

### Crash Report

https://gist.github.com/Batt11/06f9c26e9db6eb2de02a7abcce23db75

**Comment by Qelifern** [comment]
Fixed in 1.19.2 3.6.5
