### ISSUE TITLE
Diamond Furnace Crashing server and clients

### ISSUE THREAD

**Issue by Zelioth** [Qelifern/IronFurnaces#146]
### Forge Version

43.2.3

### Fabric Version

0.0.00

### Iron Furnaces Version

3.6.4

### Describe your issue

Hello, I am the creator and developer of Friends United. I have ran and distributed a version of our pack for servers to be ran and recently I've had issues and had others come to me regarding issues with crashing from the diamond furnace.  

### Crash Report

https://gist.github.com/Zelioth/b39d25da5cc0e38e88656a2648468b75

**Comment by Qelifern** [comment]
Fixed in 1.19.2 3.6.5

**Comment by Shybella** [comment]
Can this fix be added to 1.18.2?
