### ISSUE TITLE
Turning on comparator mode on a server bricks the server

### ISSUE THREAD

**Issue by RSNFreud** [Qelifern/IronFurnaces#148]
### Forge Version

40.1.93

### Iron Furnaces Version

3.3.3

### Describe your issue

When changing redstone mode to comparator on a diamond furnace, the block sends the game into a crash loop. Only happens when on a server and not on singleplayer - This is on 1.18.2

### Crash Report

https://mclo.gs/z3DkKSA

**Comment by Sonamiya** [comment]
Same here. Was about to make a issues post but am jsut going to bump here instead.

Game version however was 1.19.2.
 Also on a server.

**Comment by Shybella** [comment]
Can confirm this does cause the server to crash on 1.18.2 latest.

**Comment by TigerWalts** [comment]
The `org.apache.commons.compress.utils.Lists` class is not installed on dedicated Forge servers.

The typical fix is for the mod to use `com.google.common.collect.Lists` instead.

---

If you need to fix a world, you can use an NBT editing tool to find the furnace's block entity data and change the `Redstone` tag to `[0, 0]`

![image](https://user-images.githubusercontent.com/33809164/227956345-a784da9a-534c-41a4-998c-934c5017948f.png)

**Comment by Aronicus** [comment]
@TigerWalts is there any simple fix for a server to install that or is it a hope the dev pushes an update?

**Comment by TigerWalts** [comment]
I've had to repair this so many times on servers that I wanted to see if I could fix this myself but the 1.18.2 and 1.19.2 branches in this repo are not up to date.

It appears to be on `3.3.0` for the 1.18.2 branch and `3.6.3` for 1.19.2 branch.

The bug was introduced into 1.20 `3.7.1` and backported. It was fixed in 1.20 `3.7.2`, but the fix was not backported.

**Comment by NoobKeksTV** [comment]
so the bug was not fixed in older versions meaning if i play on forge 1.18.2 i am stuck with it? Just broke my server with this...

**Comment by LionZXY** [comment]
Solution: https://github.com/Qelifern/IronFurnaces/issues/143#issuecomment-1894287023
