### ISSUE TITLE
Iron Furnaces JEI recipe handling is inefficient

### ISSUE THREAD

**Issue by embeddedt** [Qelifern/IronFurnaces#171]
### Forge Version

Tested on 43.2.13 (1.19.2), but should apply to any since 1.16 

### Fabric Version

N/A

### Iron Furnaces Version

3.6.5, but applies to any since 1.16

### Describe your issue

The Iron Furnaces JEI plugin is very slow at registering recipes, often taking upwards of 10 seconds in a modpack. I dug into this and found that the reason for the slowness is `AbstractFurnaceBlockEntity.getFuel` being called many times (once for each item). This is extremely slow as that function recreates a mapping of vanilla item -> burn time each time it is invoked.

I am not sure what the reason for having a custom `getBurnTime` method in Iron Furnaces is, as from what I can tell it appears to use the exact same logic as `ForgeHooks.getBurnTime`, except that the latter already caches the vanilla burn map and thus should have a much smaller performance penalty.

Here is a Spark profile showing Iron Furnaces as the most expensive plugin CPU-wise when registering recipes.

https://spark.lucko.me/5FIhCyTcca?hl=3222

**Comment by Qelifern** [comment]
Working on this, how did you use spark to profiler with Prismlauncher? Never heard of this being possible.

**Comment by embeddedt** [comment]
I started the Spark profile from inside a singleplayer world using `/sparkc profiler` and then ran `/reload`, that way it would capture the recipe reloading event.

**Comment by Qelifern** [comment]
Ah makes sense, thought you used spark to profile the game launching hehe

**Comment by embeddedt** [comment]
I actually did add a feature in ModernFix that allows doing that :stuck_out_tongue:

**Comment by Qelifern** [comment]
finally as of 4.1.6, ForgeHooks.getBurnTime got implemented.
