### ISSUE TITLE
Compat Request For Iron Furnaces PMMO 

### ISSUE THREAD

**Issue by Devilswarchild** [Qelifern/IronFurnaces#179]
### Describe your suggested feature or change

iron furnaces currently do not give smelting xp when smelting ores. pmmo assigns this stat to all machines that can cook ores. base furnace and blast furnace (base mc machine) is there any way we can get explicit compat with project mmo for this mod?

**Comment by Qelifern** [comment]
there already is, some versions have the compatibility temporarily disabled however 1.20.1-4.1.1 will have PMMO support once again when 4.1.1 is released.
