### ISSUE TITLE
i dont know if this exists or not

### ISSUE THREAD

**Issue by Minepro306** [Qelifern/IronFurnaces#186]
### Describe your suggested feature or change

![2023-10-31_15 29 34](https://github.com/Qelifern/IronFurnaces/assets/90959615/2da07732-d14a-4288-a61d-1f5a10d600fd)
i dont know if its supposed to connect or not (the cables are from applied energetics 2)

**Comment by XenoMustache** [comment]
You need a bus to interact with containers in AE2/RE.
