### ISSUE TITLE
Slow server startup caused by attempted update checks on startup

### ISSUE THREAD

**Issue by meishiffx** [Qelifern/IronFurnaces#187]
### Describe your suggested feature or change

[ Iron Furnaces Update Checker/INFO] [ir.IronFurnaces/]: Update Check done!
[ Iron Furnaces Update Checker/INFO] [ir.IronFurnaces/]: Iron Furnaces is up to date!

In the case of slow network, the process will stop for 3-5 minutes. Request a separate interface in the configuration file, not everyone needs to check for updates frequently.

**Comment by XenoMustache** [comment]
There is a config setting to disable this.
