### ISSUE TITLE
Gold Blast Furnace missing textures in the front

### ISSUE THREAD

**Issue by BugmanBugman** [Qelifern/IronFurnaces#19]
![2020-10-22_10 17 38](https://user-images.githubusercontent.com/40730042/96899542-a735dc80-1456-11eb-9a45-af4e7ece3997.png)
`[22Oct2020 10:36:23.978] [Worker-Main-8/ERROR] [net.minecraft.client.renderer.texture.AtlasTexture/]: Using missing texture, unable to load ironfurnaces:textures/block/gold_furnace_front_blast.png : java.io.FileNotFoundException: ironfurnaces:textures/block/gold_furnace_front_blast.png`

**Comment by XenoMustache** [comment]
It appears this texture is simply missing at the moment. It should be corrected in the next release! Thank you for letting us know.

**Comment by Qelifern** [comment]
Fixed
