### ISSUE TITLE
Upgrading furnaces makes it drop all items and loses all energy

### ISSUE THREAD

**Issue by Phoupraw** [Qelifern/IronFurnaces#196]
### Forge Version

47.1.44

### Iron Furnaces Version

4.1.3

### Describe your issue

Upgrading furnace in place keeps its upgrades, but drops ingredients and fuels.

Besides, upgrading furnace in place will set the rotation to the side of use.

**Comment by Qelifern** [comment]
4.1.5 update makes furnaces retain its energy. When a generator or factory augment is installed, its intended to drop its items.
