### ISSUE TITLE
Rather severe: Factory upgrades + Enabling Auto I/O on high-speed furnaces, causes  massive TPS Drops (Lag-Switch)

### ISSUE THREAD

**Issue by Burchard36** [Qelifern/IronFurnaces#199]
### Forge Version

47.2.20

### Fabric Version

N/A

### Iron Furnaces Version

4.1.4

### Describe your issue

https://spark.lucko.me/eg2nXARBFe - Here is the spark report

This error happens in ATM9 - and I was directed by the developers there to open a issue here, not sure if this is entirely iron furnaces fault but 

Players on a few of my servers have discovered a lag switch, allowing them to stall my servers thread to a halt by using furnaces such as obsidian or faster and simply enabling "Auto Input/Output" in the furnace side configuration panel

Here is a video, this might further explain the issue at hand, as i probably explained it pretty badly: https://www.youtube.com/watch?v=4GPW6dDw5fo

### Crash Report

No Crash, just lag

**Comment by Burchard36** [comment]
Yeah can we pretend I never made that grammar mistake in the title please LOL

**Comment by Qelifern** [comment]
Looking at this and trying to reproduce this behaviour. The spark link doesnt work for me.

**Comment by Qelifern** [comment]
Fixed in 4.1.5
