### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Sixdd6** [Qelifern/IronFurnaces#2]
I posted on Curseforge but figured I should put this here as well.

I'd like to request CraftTweaker support for recipes that only a specific furnace can smelt. For example a copper furnace would be able to smelt x but not y, an iron furnace could smelt x and y but not z, etc. being able to specify exactly what each furnace can do.

**Comment by XenoMustache** [comment]
I don't really think this is really necessary, but we will take this into consideration. Who knows, it could be a wonderful addition.
