### ISSUE TITLE
Stone furnace breaks when upgrading to Iron Furnace if smelting in 1.15

### ISSUE THREAD

**Issue by XenoMustache** [Qelifern/IronFurnaces#20]
When using the upgrade item to turn the stone furnace into an iron furnace, the block simply breaks and all its contents spill onto the ground if it is currently in the process of smelting something. The block still becomes an iron furnace when it is dropped, and drops as such, but the block should be upgraded in place of the stone furnace.

**Comment by Qelifern** [comment]
support for 1.15.2 closed
