### ISSUE TITLE
Rinbow linker missing

### ISSUE THREAD

**Issue by cstalker** [Qelifern/IronFurnaces#205]
### Forge Version

47.2.20

### Iron Furnaces Version

1.20.1-4.1.6

### Describe your issue

there is no rainbow linker. how does one link the rainbow furnaces now? i tried the link tool but that just sets the sid configs

**Comment by XenoMustache** [comment]
Rainbow furnace linker was removed, furnaces are automatically linked to the player when placed. When one of each type is active, the rainbow furnace gets the power generation enhancement automatically.
