### ISSUE TITLE
Augment: Experience

### ISSUE THREAD

**Issue by supertrio17** [Qelifern/IronFurnaces#206]
### Forge Version

40.2.14

### Iron Furnaces Version

3.3.3

### Describe your issue

There is no info anywhere for the Augment of Experience

I have no idea what its for except it has to do something wit experience, its not showing any new buttons when applied to the furnace, idk.

![image](https://github.com/Qelifern/IronFurnaces/assets/57882120/db52a317-e105-428b-8c30-f79604e5583d)

**Comment by XenoMustache** [comment]
This augment is a work in progress, as shown by the tooltip. It's not intended to be obtained in survival as of yet.
