### ISSUE TITLE
[1.16.4] Furnace Disappearing with Gobber Hammers

### ISSUE THREAD

**Issue by TwilightPSN** [Qelifern/IronFurnaces#22]
When you mine a block with a hammer, if the furnaces are one of the blocks in the 3x3 the furnace disappears when its broken.

**Comment by Qelifern** [comment]
Which hammer from which mod? The furnace is designed only to be destroyed by a player. The furnace is a tile-entity and should not be destroyed by hammers when mining 3x3, it should only be destroyed if the block you are starting at is the furnace block.

**Comment by TwilightPSN** [comment]
appears to happen with the hammers from the Gobber mod only

**Comment by Qelifern** [comment]
ironfurnaces-1.16.4-2.5.4 (not released as of writing this) fixes this issue
