### ISSUE TITLE
crystal furnace uncraftable

### ISSUE THREAD

**Issue by Warbringer12** [Qelifern/IronFurnaces#23]
**Describe the bug**
you made it to where the crystal furnace is uncraftable

**Versions**
- **Iron Furnaces**: 2.5.1
- **Forge**: 1.16.4

<details>
![2020-11-26_19 38 10](https://user-images.githubusercontent.com/44590540/100408115-1044dd00-301f-11eb-8c69-6dd759b096b7.png)

**Comment by Qelifern** [comment]
Fixed in 2.5.2, will publish soon
