### ISSUE TITLE
Iron Furnace didn't light up

### ISSUE THREAD

**Issue by HenryMaxler** [Qelifern/IronFurnaces#24]
**Describe the bug**
I was furnacing in a cave and I noticed the Fast Furnace lights up but when I crafted an Iron Furnace, it did not light up.

**Versions**
- Iron Furnaces: ironfurnaces-1.16.4-2.5.1
- Forge: forge-35.1.4

**Comment by Qelifern** [comment]
using FastFurnace together with IronFurnaces is not recommended, I've got no control over it and cant offer support.

**Comment by HenryMaxler** [comment]
Actually I think it might be Optifine.  I put them in by themselves and once the furnace went out, it didn't generate light anymore.

**Comment by Qelifern** [comment]
In ironfurnaces-1.16.4-2.5.3 the way the furnace updates light has changed (same as FastFurnace) so this problem is probably fixed.

**Comment by HenryMaxler** [comment]
No, it's not working :(

**Comment by Qelifern** [comment]
Hmmm, I'll leave this issue open altough I dont plan working on figuring out why optifine does this.

**Comment by Qelifern** [comment]
So Optifine uses whats called Overwrite Mixins which means that they NUKE the entire minecraft function that is probably used for blockstate updates and changes the vanilla mechanics of it.
Basically: I cant do anything about this lol. (Unless I import Optifine and include it as a dependency and NUKE the function myself; which I wont)
Conclusion: Optifine is garbage sometimes.
