### ISSUE TITLE
Iron Furnaces disregard smelting time in recipes

### ISSUE THREAD

**Issue by Miner239** [Qelifern/IronFurnaces#26]
**Describe the bug**
Iron furnaces smelts things as if all of them has 10s smelting time.

**To Reproduce**
1. Get a mod that has smelting recipes with non-standard time cost (e.g. Vanilla Food Pantry)
2. Smelt the items in both regular furnace and iron furnaces
3. See that fuel consumption differ

**Versions**
- **Iron Furnaces**: 2.5.6
- **Forge**: 35.1.28

**Comment by Qelifern** [comment]
This is the remains of the old versions of Minecraft when the furnace only had 200 ticks as the smelting time. Next update will override the smelt time with the recipe smelt time if the recipe is lower than 200 ticks, then it will subtract an amount from that smelt time depending on which furnace you are using. 
(This feature is working for blasting and smoking recipes if I'm not mistaken)
Example: Recipe is 120 ticks, calculated ticks if Iron Furnace 120 - (200 - ironFurnaceSpeed) = 120 - 40 = smelt time 80 ticks.

**Comment by Miner239** [comment]
Is it not better to just make furnace speed config some kind of a multiplier of the standard furnace speed so that recipe tick costs are consistent for every recipe and furnace? That formula seems to result in a 40 tick recipe smelt instantly on a <160 tick furnace (40 - (200 - 160) = 0)... and, if I'm reading this correctly, longer recipes do not benefit at all when using better furnaces?

**Comment by XenoMustache** [comment]
This functionality was added in the newest version of Iron Furnaces.
