### ISSUE TITLE
Furnace Upgrade error

### ISSUE THREAD

**Issue by Dr-WeiAL** [Qelifern/IronFurnaces#27]
Iron to silver furniture upgrade is actually copper to silver furniture upgrade
Copper to silver furniture upgrade is actually iron to silver furniture upgrade
![image](https://user-images.githubusercontent.com/47446553/103567127-3141fd00-4efe-11eb-8723-d2266aecab66.png)
![image](https://user-images.githubusercontent.com/47446553/103567146-38690b00-4efe-11eb-86d5-f6c3ba4e1fe2.png)

These two are wrong

It's not just a language error
The item map is also wrong

(This is Google Translate, please forgive me if there is any mistake)

**Comment by Qelifern** [comment]
2.5.7+ fixes this
