### ISSUE TITLE
Hoppers do not take items out of furnace

### ISSUE THREAD

**Issue by Poke5555** [Qelifern/IronFurnaces#3]
using IF 1.14.3-1.5.0 on forge 27.0.57.
hoppers will input items into the furnace but items cannot be removed from the furances with hoppers

**Comment by lehjr** [comment]
The problem is in BlockIronFurnaceTileBase, specifically slots_side definition is mixed up with that of slots_bottom (see vanilla code)
this:
```
    private static final int[] slots_top = new int[]{0};
    private static final int[] slots_side = new int[]{2, 1};
    private static final int[] slots_bottom = new int[]{1};
```
should be like this:
```
    private static final int[] slots_top = new int[]{0};
    private static final int[] slots_bottom = new int[]{2, 1};
    private static final int[] slots_side = new int[]{1};
```
