### ISSUE TITLE
Crash with 2.5.8 on multiplayer server startup

### ISSUE THREAD

**Issue by Letoric** [Qelifern/IronFurnaces#31]
**Versions**
Included in crash log

Crash Log
https://pastebin.com/xas7rzdf

**Comment by Qelifern** [comment]
Try using 1.16.5-2.6.1 and see if it works.

**Comment by XenoMustache** [comment]
Closing due to stale issue. If any future problems occur simply reopen.

**Comment by Letoric** [comment]
Can you update smoothly from 2.5.6 to any build without it causing crashes
yet?
