### ISSUE TITLE
Rainbow Furnace Speed

### ISSUE THREAD

**Issue by ghost** [Qelifern/IronFurnaces#33]
**Describe the bug**
The Rainbow Furnace is set in the config by default to take 200 ticks per operation (same as a standard furnace). Given its recipe... this doesn't make any sense at all. If anything, it should be the fastest furnace in the mod!

**To Reproduce**
1. Open ironfurnaces.toml
2. Read line 73

**Expected behavior**
The Rainbow Furnace should be a step up in speed from the Netherite Furnace.

**Versions**
- **Iron Furnaces**: 2.5.8
- **Forge**: 35.1.37

**Comment by Qelifern** [comment]
Agreed, next update will make the Rainbow Furnace a speedy boi by default.

**Comment by ghost** [comment]
Hell yeah, speedy boi time

(also sorry about adding the wrong label lol)
