### ISSUE TITLE
Compatibility with FastFurnace mod

### ISSUE THREAD

**Issue by Aspyro** [Qelifern/IronFurnaces#35]
## What should be added or changed?

As the title say, trying to make a compatibility with ***FastFurnace*** mod

## Why should this be done?

In my modpack i have both mods. The problem is when I try to apply a *stone to iron upgrade* on a vanilla furnace (not that vanilla due to FastFurnace I suppose overriding the furnace). This won't upgrade and a message will appear suggesting how to get the material back.

![2021-02-02_13 48 46](https://user-images.githubusercontent.com/37420016/106602955-f9aa8d00-655d-11eb-9dd2-985c4d90a498.png)

Due to that, I took the decision to remove all the upgrades of the mod in the modpack. The crafts for the upgraded furnaces still exist so it's okay, but that would surely make it more convenient to use the upgrades directly on the furnaces.

Is this the right place for this issue ? Or should I make it in fast furnace issues tracker too ?

**Comment by Qelifern** [comment]
It does work, however in the past it has created ghostblocks and what not also the stone furnace tileentity might not get deleted and timing issues and its just a nightmare, and thats why, but it does work so its not on the FastFurnace side of things.

**Comment by Aspyro** [comment]
Applying the upgrade works ? Is that what you want to say ?
Because on my tests it doesn't.
Or maybe you changed it in-between ?
