### ISSUE TITLE
Allow the Wireless Heat Receiver to work in non Iron Furnace furnaces

### ISSUE THREAD

**Issue by BobVarioa** [Qelifern/IronFurnaces#36]
## What should be added or changed?
Title. Maybe It could be a config option as well.

## Why should this be done?
I tried to make a good reason for this but to be honest It just would be cool.

**Comment by XenoMustache** [comment]
Sadly this isn't possible, the only reason why the wireless receiver even works with our furnaces is because they are specifically programmed with instructions on what to do with the item. This wouldn't work for generic fuel slots from the vanilla game or from other mods.
