### ISSUE TITLE
Hoppers don't work with custom furnaces.

### ISSUE THREAD

**Issue by Ahrkonh** [Qelifern/IronFurnaces#37]
**Describe the bug**
items do not transfer when trying to use hoppers or hopper like devices i.e. item cables like those in the cyclic mod with any kind of furnace but the standard stone furnace.

**To Reproduce**
1.place a hopper feeding into a chest
2.place a furnace other than stone on top of the hopper.
3.smelt something and then check the furnace for the finished product to see that it has not transfered.

**Expected behavior**
automated smelting process i.e. ore from chest through the hopper into the furnace smelted items from the furnace through the hopper into the chest.

**Versions**
- **Iron Furnaces**: 1.16.5-2.6.3
- **Forge**: 36.0.14
- **Fabric**: x.x.x
- **MC**: 1.16.5

<details>
i dont know if this matters or not but I'm using the curseforge launcher with the modpack all the mods 6
  Log goes here
<details>

**Comment by XenoMustache** [comment]
Why didn't you use the bug report issue template? We don't know what version of the mod you're trying to use or whether it's fabric or not. Please update this issue accordingly or it will be closed.

**Comment by Ahrkonh** [comment]
ok fixed sorry about that i had posted it on mobile so i didnt see the format

**Comment by XenoMustache** [comment]
By default all furnace faces are unconfigured. This isn't a bug, simply open the menu and configure them manually. This may change in the future to have the furnaces configured like a normal furnace by default.
