### ISSUE TITLE
Update Message Keeps Appearing

### ISSUE THREAD

**Issue by MrTailson** [Qelifern/IronFurnaces#38]
**Describe the bug**
Even though I have the most updated version of the mod, when joining into a world, the mod displays a message saying it needs to be updated, even telling me my current version is an old one, when I know it isn't. It takes me to the download page to download the newest version, but I already have it.
**To Reproduce**
1.
2.
3.

**Expected behavior**

**Versions**
- **Iron Furnaces**: 1.16.5-2.6.3
- **Forge**: x.x.x
- **Fabric**: x.x.x

<details>
  <summary>Crashlog</summary>
  Log goes here
<details>

**Comment by Qelifern** [comment]
2.6.3 might have had 2.6.2 update numbers, should be fixed in later versions.
