### ISSUE TITLE
Ticking Block Entity Error when using Gold Furnace

### ISSUE THREAD

**Issue by I-Am-Da-Fish-Man** [Qelifern/IronFurnaces#41]
**Describe the bug**
As soon as the first material loaded into the furnace is supposed to finish smelting, the server crashes and goes into a never-ending crash loop.

**To Reproduce**
1. Put a stack of clay into a gold furnace over a stack of coal 
2. Wait for the first clay to turn into a brick
3. Cry when the server turns into a brick instead

**Expected behavior**
Put in clay, get out brick.

**Versions**
- **Iron Furnaces**: 1.16.1 - 2.1.1
- **Forge**: 32.0.108
- **Fabric**: x.x.x

<details>
  <summary>Crashlog</summary>
18.02 23:06:36 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
18.02 23:06:36 [Server] INFO net.minecraft.crash.ReportedException: Ticking block entity
18.02 23:06:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
18.02 23:06:36 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B}
18.02 23:06:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
18.02 23:06:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
18.02 23:06:36 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
18.02 23:06:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
18.02 23:06:36 [Server] INFO Caused by: java.lang.NullPointerException
18.02 23:06:36 [Server] INFO at net.minecraft.inventory.IRecipeHolder.func_201561_a(SourceFile:27) ~[?:?] {re:classloading}
18.02 23:06:36 [Server] INFO at ironfurnaces.tileentity.BlockIronFurnaceTileBase.smeltItem(BlockIronFurnaceTileBase.java:284) ~[?:2.1.1] {re:classloading}
18.02 23:06:36 [Server] INFO at ironfurnaces.tileentity.BlockIronFurnaceTileBase.func_73660_a(BlockIronFurnaceTileBase.java:223) ~[?:2.1.1] {re:classloading}
18.02 23:06:36 [Server] INFO at net.minecraft.world.World.func_217391_K(World.java:533) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
18.02 23:06:36 [Server] INFO at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:364) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
18.02 23:06:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
18.02 23:06:36 [Server] INFO ... 5 more
18.02 23:06:37 [Multicraft] Server shut down (running)
18.02 23:06:37 [Multicraft] Restarting crashed server in 10 seconds
<details>

**Comment by Qelifern** [comment]
Please consider updating from 1.16.1, as this issue was fixed in later versions.
