### ISSUE TITLE
Iron Furnaces not allowing collection of stored exp

### ISSUE THREAD

**Issue by Lovatic123** [Qelifern/IronFurnaces#43]
Iron Furnaces not allowing collection of stored exp

Vanilla blast and furnaces store the exp from whatevers been smelted in it when connected to hoppes, which immediately takes out any smelted items. This exp can be collected by adding a piece of redstone dust next to the furnace, connected to a lever, which when left on will keep the smelted items from going down the hopper, so you can collect the item manually. This will give you all the exp stored in the furnace. (see pictures below)

Furnaces from the mod Iron Furnaces do not allow this, as the redstone component only affects the furnace being on/off. This means a lot of exp is being wasted/lost when the furnaces are part of an autosmelting system.

Minecraft version: 1.16.5
IronFurnaces version: 1.16.5 - 2.6.4
Forge version: 1.16.5-forge-36.0.42

![2021-02-23_14 19 54](https://user-images.githubusercontent.com/20798024/108849312-4ffd6f80-75e2-11eb-9a4a-57dbe0cd30f6.png)
![2021-02-23_14 20 05](https://user-images.githubusercontent.com/20798024/108849318-512e9c80-75e2-11eb-90e3-35c729aa0891.png)

**Comment by Qelifern** [comment]
An "XP mode" could be added to the redstone mode options which would make it act this way, or simply the "redstone ignored" would replicate how the vanilla furnace does this. Will implement in the next version. Thank you

**Comment by Qelifern** [comment]
The way the furnaces handle XP has been changed, read changlelog for more info.
