### ISSUE TITLE
Output got voided if Storage Drawers drawers' full/no slot of the same kind

### ISSUE THREAD

**Issue by ChromaPIE** [Qelifern/IronFurnaces#44]
**Describe the bug**
Items produced from an Iron Furnace furnace which is set to auto tranfer outputs into a Storage Drawers drawer which lacks slots or space for them would cause them to be voided, instead of staying in the output slot of the furnace. Please confirm if it's exactly Iron Furnace's issue, otherwise this issue is okay to be closed then I'll turn to Storage Drawers' repo.

**To Reproduce**
1. Set any side of an IF furnace to auto output mode, then place a SD drawer right beside the corresponding side;
2. Stuff things into the drawer, make sure it has no space left for outputs;
3. Run the furnace;
4. The outputs from the furnace got voided.

**Expected behavior**
The furnace should've keep things inside if it's impossible for the target drawers to contain more.

**Versions**
- **Iron Furnaces**: 2.6.4
- **Forge**: 36.0.46

**Comment by Qelifern** [comment]
I have done some testing and it seems the 1x1 drawer has 2 slots, one that stores the items and one that just voids anything that gets put into it. Since I'm looping through all the slots, when the item doesnt match the 1st slot or the 1st slot is full it will move on to the 2nd slot which is the voidslot.

**Comment by bobthebigbat** [comment]
I'm not familiar with Forge Modding, but shouldn't StorageDrawers (and every other inventory suitable for auto output) provide an overloaded function/method that you call to insert x number of items? I just think it strange that it should be your responsibility to directly access the inventories of connected blocks.

Like in psudocode it would go something like this ...


If AutoOutput is enabled
   Loop through output slots
      Test if connectedblock is of type inventory
      num_inserted := connectedblock.insertitem(furnace.item_id, furnace.number_in_output_slot)
      furnace.number_in_output_slot := furnace.number_in_output_slot - num_inserted
   End Loop
End If

Just repeating - I don't know anything about Forge/Minecraft programming, but having experience with object oriented programming it seems like inserting items is something the connected inventory should be doing and just returning a result.
