### ISSUE TITLE
Lava bucket in iron furnace

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [Qelifern/IronFurnaces#45]
**Describe the bug**
Not sure if this is a feature request or a bug. Both seem possible.

Cannot output the empty bucket once the lava is consumed.

**To Reproduce**
1. Place lava bucket inside iron furnace.
2. Wait for the iron furnace to consume / start consuming the lava.
3. Empty bucket is now stuck.

**Expected behavior**
Option to output the fuel slot.

**Versions**
- **Iron Furnaces**: 2.6.4
- **Forge**: 36.0.46
- **Fabric**: N/A

<details>
  <summary>Crashlog</summary>
  N/A
<details>

**Comment by Shantarr** [comment]
Same issue.

**Comment by Qelifern** [comment]
will work in 2.6.7

**Comment by Shantarr** [comment]
Excellent, thank you so much!
