### ISSUE TITLE
Wireless heat transmitter loses power on world load

### ISSUE THREAD

**Issue by raventrickster** [Qelifern/IronFurnaces#46]
**Describe the bug**
In single player, the wireless heat transmitter loads with no power in it's internal buffer, regardless of current internal buffer prior to world shutdown.

**To Reproduce**
1. Charge the Wireless Heat Transmitter
2. Save and Quit to title
3. Launch the world
4. Wireless Heat Transmitter no longer has any power buffer

**Expected behavior**
Wireless Heat Transmitter would maintain it's internal buffer between play sessions

**Versions**
- **Iron Furnaces**: 2.6.5
- **Forge**: 36.0.45
- **Fabric**: NA

<details>
  <summary>Crashlog</summary>
  Log goes here
<details>

**Comment by Guswut** [comment]
As a quick note, this only appears to affect the block version and not the item version.

Not sure if that is important for this bug, although for everyone else you can break it before leaving your world and replace it when you return as a workaround until this gets patched.

Thanks!

**Comment by Qelifern** [comment]
working on a fix

**Comment by Qelifern** [comment]
2.6.7 fixed this
