### ISSUE TITLE
"Allthemodium" furnaces and upgrades still spawnable even if mod doesn't exist

### ISSUE THREAD

**Issue by shinji257** [Qelifern/IronFurnaces#47]
**Describe the bug**
Even when the allthemodium mod is not present the items can still be spawned either by a user (give command) or via a lootbag system even though they are disabled in JEI and from Creative tabs.

**To Reproduce**
1. Make sure allthemodium mod is not present
2. Use `/give @p ironfurnaces:allthemodium_furnace`

**Expected behavior**
These items should not be registered as the mod they rely on to even be crafted are not present.

**Versions**
- **Iron Furnaces**: 2.6.6
- **Forge**: 36.1.2
- **Fabric**: N/A

<details>
  <summary>Crashlog</summary>
-- not a crash --
<details>

**Comment by XenoMustache** [comment]
This is not a bug, the items are still registered for safety reasons even without the Allthemodium mod present.
