### ISSUE TITLE
blocking rei

### ISSUE THREAD

**Issue by zaze06** [Qelifern/IronFurnaces#48]
**Describe the bug**

**To Reproduce**
1. install iron furnce forge and rei forge
2. start minecarft
3. and rei doesn't work

**Expected behavior**
rei works and I askt the rei guse and that sed that iron furnce stoped the recipe loding

**Versions**
- **Iron Furnaces**: 1.16.5-2.6.7
- **Forge**: 26.1.0

<details>
  <summary>Crashlog</summary>
  https://gist.github.com/zaze06/57b034f4087e80790b0e409a88e51f1a
<details>

**Comment by Qelifern** [comment]
IronFurnaces does not currently support Roughly Enough Items.
It does however support Just Enough Items.
