### ISSUE TITLE
Crash with PMMO

### ISSUE THREAD

**Issue by MrTailson** [Qelifern/IronFurnaces#49]
**Describe the bug**
When starting up the game, an error message stating that iron furnaces only supports PMMO 3 and above, yet it tells me the version of PMMO I currently am using is 3.53.2 , which I believe is above 3 and should still work, right?

**Versions**
- **Iron Furnaces**: 2.6.7
- **Forge**: 36.1.13
- **Fabric**: x.x.x

<details>
  <summary></summary>
  [latest.log](https://github.com/Qelifern/IronFurnaces/files/6378135/latest.log)Crashlog
  
  I never know if I'm implementing the crash log correctly.
<details>

**Comment by skybix** [comment]
I am getting the same bug.
I am using:
forge: 36.1.16
ironfurnaces 2.6.7
project mmo 3.54.1

**Comment by didis54** [comment]
Adding a screenshot of the message
![image](https://user-images.githubusercontent.com/3106344/117843371-0b977c80-b27f-11eb-8181-0b6f39347e11.png)

**Comment by Qelifern** [comment]
When using forge 36.1.4 this doesn't happen, however in later versions of forge I get the same error.
This is fixed with didis54 method.
ironfurnaces-1.16.5-2.6.8 will be up soon on curseforge.
