### ISSUE TITLE
Augment: Speed causes power to be continually wasted if using it with Wireless Heat Receiver with low power available.

### ISSUE THREAD

**Issue by TopPercentageRattata** [Qelifern/IronFurnaces#51]
**Describe the bug**
Augment: Speed causes 2x fuel to be used, and thus 2x energy to be used if used with Wireless Heat Receiver. Normally not a problem but if low power is available in Wireless Heat Transmitter, for example if using some low energy windmills/waterwheels/solar panels from mods, then smelting constantly stops and starts, due to furnace trying to smelt when only having half the energy available to smelt an item. Thus it only gets items halfway smelted before failing and restarting smelting progress.

**To Reproduce**
1. Have a furnace with augment:speed and wireless heat receiver and transmitter hooked up with items ready to smelt
2.  Start sending a small trickle of power to wireless heat transmitter from some low energy producing thing such as a windmill from IE
3. Watch furnace only smelt items halfway before failing, and continuously wasting power.

**Expected behavior**
Should wait for (the 2x normal)power to be available before starting smelting

**Versions**
- **Iron Furnaces**: 2.6.8
- **Forge**: 36.1.18

**Comment by Qelifern** [comment]
Currently, with the speed augment the calculation is this: per 2000 RF = 0.5 Items smelted
I am changing it to 4000 RF = 1 Item smelted so this issue wont happen.

Thanks for submitting.
