### ISSUE TITLE
Buggy interaction with 'Auto Input' and reduced stack sizes from Iguana Tweeks

### ISSUE THREAD

**Issue by SweetlilTrinket** [Qelifern/IronFurnaces#53]
**Describe the bug**
I have the latest version installed in my modpack and I suspect this is a problematic interaction with the reduced stack sizes from the mod Iguana Tweeks Reborn, whenever I place a hopper or chest above the furnace and fill it with stacks of ore to use the "Auto Input" feature it will automatically suck in every ore of that type and delete all but the stack its smelting. I think the problem might be that the furnace things the stacksize should be larger and therefor tries to shove them in, but since iguanas reduces the sizes the excess are just getting voided. Can be isolated I believe.

EDIT: The same seems to be true with the 'Auto Output' feature.

**To Reproduce**
1.Latest version of both mods installed 
2.Use hopper or chest and auto input feature to process ore
3.All but the stack in the furnace will be deleted as they are filtered in

**Expected behavior**
I expected it to recognize the reduced stack size and auto input as normal.

**Versions**
- **Iron Furnaces**: 1.16.5 2.6.8
- **IguanaTweaksReborn**: -2.6.0-mc1.16.5
- **Forge**: 36.1.32
- **Fabric**: x.x.x

<details>
  <summary>Crashlog</summary>
  No crash
  ```
  Log goes here
  ```

**Comment by Qelifern** [comment]
Spot on, Hard-coded 64 should be ItemStack.getMaxStackSize() instead.

Thank you for submitting.
2.6.9 Fixes this.
