### ISSUE TITLE
Output got stopped if Mekanism bin which has  more than 64 items.

### ISSUE THREAD

**Issue by 1048139283** [Qelifern/IronFurnaces#55]
**Describe the bug**
Items produced from an Iron Furnace furnace which is set to auto tranfer outputs into a Mekanism bin which has  more than 64 items would cause them to be failed to output, staying in the output slot of the furnace. Please confirm if it's exactly Iron Furnace's issue, otherwise this issue is okay to be closed then I'll turn to Mekanism' repo.

**To Reproduce**
1.Set any side of an IF furnace to auto output mode, then place a MEK drawer right beside the corresponding side;
2.Stuff things into the bin, make sure it has more than 64 items;
3.Run the furnace;
4.The outputs from the furnace got stopped.

**Expected behavior**
The furnace should've outputted items to the bin.

**Versions**
- **Iron Furnaces**: 2.6.9
- **Forge**:36.1.65
- **mek**:10.0.21

**Comment by Qelifern** [comment]
3.6.3 fixes this
