### ISSUE TITLE
Server Ticking freeze then crash

### ISSUE THREAD

**Issue by spoorn** [Qelifern/IronFurnaces#56]
**Describe the bug**
Server freeze then crash when getting speed.  May be related to FastSuite according to logs?

**To Reproduce**
Server freezes when I placed a double chest between 2 iron furnaces, not sure if reproducible

**Expected behavior**

**Versions**
- **Iron Furnaces**: 2.6.9
- **Forge**: 1.16.5-36.2.2

[crash-2021-08-04_01.54.49-server.txt](https://github.com/Qelifern/IronFurnaces/files/6929972/crash-2021-08-04_01.54.49-server.txt)

**Comment by Qelifern** [comment]
https://github.com/Qelifern/IronFurnaces/issues/58

Duplicate issue
