### ISSUE TITLE
Ironfurnace mod causes heavy lag even while idle

### ISSUE THREAD

**Issue by twothe** [Qelifern/IronFurnaces#58]
https://github.com/Qelifern/IronFurnaces/blob/d9f7f379de089916433df58b87d12504f0a24312/src/main/java/ironfurnaces/tileentity/BlockIronFurnaceTileBase.java#L134

Even while idle the referenced code keeps searching through all recipes on every tick, which causes [heavy lag](https://spark.lucko.me/wyAIddQ11I).

If there is no input the furnace should not do anything.
If it is busy it should cache the recipe, because it is very likely that the same one will be used for several minutes.

**Comment by Ki-Tan2934** [comment]
This is a problem that needs sorting

**Comment by Qelifern** [comment]
Working to get this fixed ASAP

**Comment by twothe** [comment]
Applying a LRU cache for the recipes might be a good and fast solution. Generally speaking there are always only a hand full of recipes that are used most of the time, so having a cache for those should be very beneficial for performance.

**Comment by Ki-Tan2934** [comment]
Send file here when it's ready for testing

**Comment by Qelifern** [comment]
https://drive.google.com/file/d/1r5tx8Pw8GTb6yISqX6O2Z0bmSRS_HHgm/view?usp=sharing

mappings are changed to official mojang mappings so some things might be broken (fire not displaying correctly in gui for example)

try it out and thanks for the help 👍

**Comment by Ki-Tan2934** [comment]
Seems it's up to 20x better
https://spark.lucko.me/zJX6CcpFk5 ( not comparable to last profile )
Machine seem to use 7 us/t when idle now and not 90 to 170

**Comment by Ki-Tan2934** [comment]
single maxed-out smelter still seems kinda bad
![image](https://user-images.githubusercontent.com/58880823/130138170-36e6a869-a6b1-4bf3-9d05-884fff082ec6.png)
https://spark.lucko.me/cnu1Qog968

Possibly an upgrade or a config to disable xp would be nice as well. had a couple of time a overflowing smelter crippling a server

**Comment by Qelifern** [comment]
Thats probably the System.out.println(""); I have all around the place in the tick method.

**Comment by Ki-Tan2934** [comment]
Gonna do another with a bunch so maybe something sticks out more

**Comment by Qelifern** [comment]
https://drive.google.com/file/d/1udWxJYmHC8gqD1F68jkXW0B2K1W6H-mh/view?usp=sharing

This is one without println stuff, dunno why I included them in a build.

**Comment by Ki-Tan2934** [comment]
https://spark.lucko.me/MM1XNHQo0r with more furnaces

Will test that new build now

**Comment by Qelifern** [comment]
👍

**Comment by Qelifern** [comment]
BlockIronFurnaceTileBase.setRecipeUsed() needs some work ⌨️

**Comment by Ki-Tan2934** [comment]
Config of furnaces seem to reset when changing to the updated jar

Here a profile of the furnace setup maxed out https://spark.lucko.me/TBiXdJycZX
![image](https://user-images.githubusercontent.com/58880823/130141165-6e32b166-682e-451e-8e1a-a755d46e85e4.png)

**Comment by Qelifern** [comment]
Yup, BlockIronFurnaceTileBase.setRecipeUsed() causing problems with Unobtainium furnaces.

**Comment by Ki-Tan2934** [comment]
Big block of idle furnaces seem to use half as much us/t

**Comment by Ki-Tan2934** [comment]
![image](https://user-images.githubusercontent.com/58880823/130141676-e6efc971-aed4-4ce3-8f19-839139d10279.png)
Before was 4/9us/t

**Comment by Qelifern** [comment]
https://drive.google.com/file/d/1DnxUQxH197fGKx04lGkAZ_ZMIWYNhupx/view?usp=sharing

This one I seperated the XP check and the setRecipeUsed, I think it fixed the Unobtainum/any other furance that smelts multiple items at once

**Comment by Ki-Tan2934** [comment]
Was me to do a test with it smelting two different ore?

**Comment by Ki-Tan2934** [comment]
It might of been smelting the coal before

**Comment by Qelifern** [comment]
Oh yes please, might be different.

**Comment by Qelifern** [comment]
Also try the new jar I sent if you have time, and try with unobtainium furnaces, it should be better.

**Comment by Ki-Tan2934** [comment]
This is a profile of multiple ore smelting https://spark.lucko.me/s5mqWzBxAq
![image](https://user-images.githubusercontent.com/58880823/130142548-79d2f1ab-4b7e-48b9-bc5d-07496c89cf2a.png)
Going to try the above version now give 10 mins or so

**Comment by Qelifern** [comment]
👏 👏 👏 👏 
Thank you

**Comment by Ki-Tan2934** [comment]
don't think the pipz round-robin setting should mess with the result

**Comment by Ki-Tan2934** [comment]
![image](https://user-images.githubusercontent.com/58880823/130143888-44dacbe7-6e45-4cf1-9a18-0c3dcce92aa5.png)
the improvement seems to good to be real
https://spark.lucko.me/OuOPDSd8nJ

Gonna dig a little

**Comment by Qelifern** [comment]
LMAO gamer moment

**Comment by Ki-Tan2934** [comment]
what did you do to make it that different?

**Comment by Qelifern** [comment]
Basically what was going on was a for loop that looped for the amount of items smelted at once, and inside that loop was another loop going through all the recipes, checking for if the XP should be reset.

So what I did was I just split them up, now they are two loops outside of eachother.

`for (int i = 0; i < 64; i++)
{
  for (int i = 0; i < ???; i++)
  {
   This is what I had before rofl.
  }
}`

**Comment by Qelifern** [comment]
So it does make alot of sense, I just hadnt noticed it before since I did most of my testing on furances that are only able to do one item at a time.

**Comment by Ki-Tan2934** [comment]
Would a no XP option make it even better then?

**Comment by Qelifern** [comment]
Probably, it would take out another Java search

**Comment by Qelifern** [comment]
ReferencePipeline.findFirst()16.84% : this would be gone

**Comment by Ki-Tan2934** [comment]
Seems iron furnaces is the go to mod now then. Not sure how many people actually use the xp from the furnaces. I've seen a lot of max integer XP blocks around the furnaces

**Comment by Qelifern** [comment]
Yeah that should've been before, 2.6.9 does have the XP check in place.

**Comment by Ki-Tan2934** [comment]
Are the furnaces meant to throw out xp every now and then?

**Comment by Qelifern** [comment]
XP should be spat out after 10 different smelts or 100000 total smelts of one item

**Comment by Qelifern** [comment]
Thats default atleast, can be changed in config.

**Comment by Ki-Tan2934** [comment]
upto 2617 levels just being near them

**Comment by Qelifern** [comment]
XD

**Comment by Ki-Tan2934** [comment]
lol when you die you still have 2617 levels

**Comment by Qelifern** [comment]
Yeah thats the power of smelting 64 items almost every tick times how many furnaces you have. lol

**Comment by Ki-Tan2934** [comment]
19

**Comment by Ki-Tan2934** [comment]
surprised the lag difference was so much

**Comment by Ki-Tan2934** [comment]
it Even lowed the pipz lag some how

**Comment by Qelifern** [comment]
yeah very surprising, although Java isnt known to be the fastest at searching through a collection of stuff, so it does kinda makes sense XD

**Comment by Qelifern** [comment]
Wait what, it lowered the pipes aswell❓ ❓ ❓

**Comment by Ki-Tan2934** [comment]
Yeah, don't get that. maybe the furnaces act slightly faster so the pipes input faster

**Comment by Qelifern** [comment]
Could be

**Comment by Ki-Tan2934** [comment]
Like the main reason for hoppers lagging is them trying to force into a full container and it keeps trying

**Comment by Ki-Tan2934** [comment]
If testing is done I'm heading off to bed

**Comment by Qelifern** [comment]
Yup I'm comfortable with a beta build upload to curse, thanks alot <3

**Comment by Qelifern** [comment]
Will keep issue open if anything comes up

**Comment by twothe** [comment]
> yeah very surprising, although Java isnt known to be the fastest at searching through a collection of stuff, so it does kinda makes sense XD

Java searching through collections is pretty fast if the correct algorithm is used. What Forge does is to loop through the entire list (which is very long with ATM6) instead of doing a hash lookup.

**Comment by Ki-Tan2934** [comment]
Should inspect augment speed upgrade they seem to make a lot of lag 
Within a rainbow furnace 939 us/t
Without in a rainbow furnace 6us/t

**Comment by Ki-Tan2934** [comment]
And it's still slower than a unobtainium furnace without

**Comment by Ki-Tan2934** [comment]
Made an actual balancer this time so the furnaces switch between two ores https://spark.lucko.me/EjoUws2Kjc
![image](https://user-images.githubusercontent.com/58880823/130225558-4af0d126-052d-46c9-b5b0-5a7f927085d0.png)

**Comment by Ki-Tan2934** [comment]
![image](https://user-images.githubusercontent.com/58880823/130228027-f833e725-2370-4277-b084-3d58d284af5a.png)
https://spark.lucko.me/P1VLCqhb06
With speed upgrades


![image](https://user-images.githubusercontent.com/58880823/130228418-acd3fe02-b526-488a-a6c0-a81250dcf952.png)
Without speed upgrades
https://spark.lucko.me/tunxYBga9C
Seems it is not the speed upgrades

**Comment by Ki-Tan2934** [comment]
using curseforge version FYI

**Comment by Ki-Tan2934** [comment]
Just a little more info that was with a 10Tic switch delay for different ores

**Comment by jebjordan** [comment]
@Ki-Tan2934 how did you do that speed overlay

So as not to ping again hopefully: Thank you.

**Comment by Ki-Tan2934** [comment]
> @Ki-Tan2934 how did you do that speed overlay

https://www.curseforge.com/minecraft/mc-mods/observable

**Comment by Qelifern** [comment]
2.7.1 might've fixed this, there was an issue where the speed could be set below 1.

**Comment by Ki-Tan2934** [comment]
Going to test now

**Comment by Ki-Tan2934** [comment]
https://spark.lucko.me/Yv20BWsehO Here updated spark without speed upgrades

**Comment by Ki-Tan2934** [comment]
That is with a furnace just swapping between two ores

**Comment by twothe** [comment]
> That is with a furnace just swapping between two ores

I strongly recommend to use a LRU cache for the furnace: the implementation is easier, and with a hashmap lookup you get the recipe instantly no matter how big the list is.

**Comment by Qelifern** [comment]
working on implementing a LRU cache, for 1.17.1 versions

**Comment by Ki-Tan2934** [comment]
1.16.5 finished now?

**Comment by Qelifern** [comment]
1.16.5-2.7.5 is up with a LRU Cache implementation
as well as 1.17.1-2.8.2, also with LRU cache
I dont know how much memory it will use, I've set the range in the config to be between 1-100 and as default the size of the cache is 10
Currently the cache wont be saved with NBT
I've done some light testing with spark and yes it should be even faster like @twothe said :)

**Comment by twothe** [comment]
Well done =)

One things on the code: Maps have the `computeIfAbsent` method, which allows to greatly simplify the code, as you can automatically pull the recipe from the manager if it is not yet in the cache.

    int cookingSpeed = cache.computeIfAbsent(item, this::getRecipe)
        .map(AbstractCookingRecipe::getCookingTime)
        .orElse(0);

Where getRecipe is defined as

    Optional<AbstractCookingRecipe> getRecipe(Item  item) {
      return (item instanceof AirItem) 
        ? Optional.empty()
        : Optional.ofNullable(this.level.getRecipeManager().getRecipeFor((IRecipeType<AbstractCookingRecipe>) this.recipeType, this, this.level));
    }

**Comment by Qelifern** [comment]
I had no idea about that, thanks 😄

**Comment by Ki-Tan2934** [comment]
Seems about 8x to 9x better with multi smelting now
