### ISSUE TITLE
Wireless Heat Transmitter get duped and not breakable

### ISSUE THREAD

**Issue by Haddadmj** [Qelifern/IronFurnaces#59]
**Describe the bug**
Wireless Heat Transmitter when placed it is not breakable in creative and when you break it in survival you get new full one instead of the one you break

**To Reproduce**
1. Place Wireless Heat Transmitter
2. Break it
3. You will get copy of the one you break

**Expected behavior**
It supposed to break and get you the one you break

**Versions**
- Modpack : PunchPack 2.1a
- **Iron Furnaces**: 2.7.0
- **Forge**: 36.2.2

**Comment by Qelifern** [comment]
this was fixed in later versions
