### ISSUE TITLE
Kubejs added blasting recipce stopped working in 2.7.5

### ISSUE THREAD

**Issue by gtokarz** [Qelifern/IronFurnaces#61]
**Describe the bug**
After update to 2.7.5 kubejs added blasting recipes stopped working (maybe sth related to recipe cache?).

**To Reproduce**
1. install kubejs
2. add blasting recipe
3. recipe is shown in JEI, works in blast furnance but not in iron furnance with blasting augument

**Expected behavior**
Blasting recipe should work as in regular blasting furnance

**Versions**
- **MC**: 1.16.5
- **Iron Furnaces**: 2.7.5
- **Forge**: 36.2.2

**Comment by Qelifern** [comment]
2.7.7 and 2.8.4 fixes this.
Blasting Augment didn't work at all, now it does.
