### ISSUE TITLE
Wireless Heat Receiver clears all item data when item is removed from slot

### ISSUE THREAD

**Issue by XenoMustache** [Qelifern/IronFurnaces#63]
**Describe the bug**
See title.

**To Reproduce**
1. Place Heat Receiver
2. Put any item with data (such as a damaged tool) into the slot
3. Remove the item. The data is gone. The item is repaired.

**Expected behavior**
No items other than a heat transmitter should be accepted into the slot.

**Versions**
- **Iron Furnaces**: 2.7.5
- **Forge**: 36.2.4 
- **Minecraft**: 1.16.5
- (All the Mods 6 - 1.8)

**Comment by Qelifern** [comment]
Fixed 2.7.6
