### ISSUE TITLE
Good luck

### ISSUE THREAD

**Issue by itsdinkd** [Qelifern/IronFurnaces#65]
No bug report for you. dick.

**Comment by XenoMustache** [comment]
Please use the issue template when submitting reports. We have no idea what "latest mod" means.

**Comment by itsdinkd** [comment]
latest mod == Your latest version of iron furnaces. sorry you cannot comprehend that.

**Comment by itsdinkd** [comment]
If I am on a mod's github, where its just 1 mod, and not a collection, and I say latest... mod... you really can't put two in two together? dunce. Crazy how egotistical some **minecraft** devs are, lmfao.

**Comment by lexxieblack** [comment]
This is a new type of low for Minecraft players...
But to be completely transparent I came here to really take a good whiff from this stupidity. I gotta say, it's dumber than I expected.

How do you deal with this sort of thing @XenoMustache xD

**Comment by red2blue** [comment]
> 
> 
> This is a new type of low for Minecraft players...
> But to be completely transparent I came here to really take a good whiff from this stupidity. I gotta say, it's dumber than I expected.
> 
> How do you deal with this sort of thing @XenoMustache xD

Oh look, a white knight! lmfao. Sorry he couldn't comprehend a simple statement.

**Comment by itsdinkd** [comment]
> 
> 
> This is a new type of low for Minecraft players...
> But to be completely transparent I came here to really take a good whiff from this stupidity. I gotta say, it's dumber than I expected.
> 
> How do you deal with this sort of thing @XenoMustache xD

Oh look, a white knight! lmfao. Take your ass-kissing back to discord. Maybe he shouldn't label issues as "dunce" when he lacked common sense to put two to two together, to which he removed the label.
