### ISSUE TITLE
failed load with latest REI update 6.1.327

### ISSUE THREAD

**Issue by TheRanker** [Qelifern/IronFurnaces#69]
**Describe the bug**

**To Reproduce**
1.add  latest iron furnces 2.6.2
2.add REI RoughlyEnoughItems-6.1.327.jar
3.launch

**Expected behavior**
 No Crash. unable to load with latest REI update.

should load to menu screen without errors.

![image](https://user-images.githubusercontent.com/5889820/140816359-71c52e20-340e-46ae-9ad0-035e99ff35b2.png)

**Versions**
- **Iron Furnaces**: ironfurnaces-1.17.1-2.6.2-fabric.jar
- **Forge**: x.x.x
- **Fabric**: 1.17.1 Modloader 0.12.3

<details>
  <summary>Crashlog</summary>
  No Crash. unable to load with latest REI update.
  ```
  Log goes here
  ```

**Comment by Qelifern** [comment]
fixed
