### ISSUE TITLE
Augments get deleted when leaving and rejoining world

### ISSUE THREAD

**Issue by Timolino456** [Qelifern/IronFurnaces#71]
**Describe the bug**
I had two golden furnaces in my house, both had a blasting augment. When I entered my world a couple minutes ago, both didn't have their augments anymore. I tested it by spawning in two blasting augments, putting them into the slot, leaving and rejoining my world and opening the furnace inventories. They were gone. Putting them in also didn't change their texture and they also couldn't be applied by right clicking. I did not test if their effect works when they are in the augment slot, this might also not work.

**To Reproduce**
1. Put augment into furnace
2. Leave and rejoin world
3. Feel scammed and cry if playing in survival

**Expected behavior**
I guess this part should be obvious. :D

**Versions**
- **Iron Furnaces**: 2.6.5
- **Fabric**: 0.11.7

<details>
  <summary>Latest log</summary>
  
  ```
  Log goes here
  ```
[latest.log](https://github.com/Qelifern/IronFurnaces/files/7513567/latest.log)

**Comment by Qelifern** [comment]
2.6.6 fixes this
