### ISSUE TITLE
Click-through config GUI conflicting with bookmarked JEI recipes

### ISSUE THREAD

**Issue by Tapeman83** [Qelifern/IronFurnaces#72]
**Describe the bug**
You cannot click on the "auto input" and "auto output" buttons if you have recipes bookmarked in JEI, as the config for the furnace is, for some reason, click-through. 

**To Reproduce**
1. Make a furnace with a config option (with auto-input and auto-output).
2. Bookmark recipes in JEI.
3. Attempt to click on the auto-input or auto-output buttons. They will not select, since the interface is click-through, so the JEI recipes get selected instead.

**Expected behavior**
I expect the interface to supersede the bookmarked JEI recipes, since the interface is open, so that I can click on the config's button in the furnace. 

**Versions**
- **Iron Furnaces**: 2.7.7 Iron Furnaces version
- **Forge**: 36.2.4 Forge version
- Stacia Expert version 1.12.6

**Comment by XenoMustache** [comment]
This isn't really possible due to the way both mods have their interface set up. My recommendation is that if you're having issues with this, temporarily disable JEI with its keybind and access the Iron Furnace menu as you need.
