### ISSUE TITLE
1.18 furnaces reset when world is exited 

### ISSUE THREAD

**Issue by Tranquillity999** [Qelifern/IronFurnaces#76]
**Describe the bug**
A clear and concise description of what the bug is. When a world/server is closed all the furnaces reset to default and lose any items that are in them 

**To Reproduce**
1.put stuff in furnace/setup pipe config
2.save and exit
3.reload and its all gone

**Expected behavior**

**Versions**
- **Iron Furnaces**: 1.18
- **Forge**: 38.0.15
- **Fabric**: x.x.x

<details>
  <summary>Crashlog</summary>
  
  ```
  Log goes here
  ```

**Comment by uspacal** [comment]
I have the same issue. The furnace loses its input/ output configurations and items get deleted...

**Comment by riesseg** [comment]
Yeah, same here. 

Loses input/output, even the wireless heater. 
Don't need to automize the furnace to see the bug happend.

version : ironfurnaces-1.18.1-3.1.0.jar
Forge : 39.0.5

**Comment by qdesjo** [comment]
Yes, I am like you : my furnaces don't save the elements inside...
