### ISSUE TITLE
Wireless Heater Energy Issues

### ISSUE THREAD

**Issue by TheSpicePhantom** [Qelifern/IronFurnaces#8]
Mod Version: 1.8.3
Forge Version: 28.2.5
MC Version: 1.14.4

I'm having the issue that your wireless heater apparently tries to push and pull energy from 1 connection at an infinite rate. I'm having an Immersive Engineering MV connector on 1 side and it just lags out everyone that's coming close. Maybe have limited Energy Input and no Output?

**Comment by TechieJunk** [comment]
I've noticed this as well. It kills my frame rate if I have a capacitor or energy cell of any sort next to it.

Mod version: 2.0.3
Forge: 31.2.20
MC Version: 1.15.2

**Comment by Qelifern** [comment]
The Wireless Heater is an Energy Consumer, that means that the TileEntity doesn't actually pull any energy, it only recieves energy that is pushed into it from another TileEntity. Maybe it has something to do with how Immersive Engineering handles energy transfer, I'll look into this when I get time.

**Comment by Qelifern** [comment]
Tested on 1.16.1 and wasnt able to recreate the issue, RF transfer worked fine.
