### ISSUE TITLE
Items inside furnace disappears

### ISSUE THREAD

**Issue by ghost** [Qelifern/IronFurnaces#81]
The bug is your item gets deleted when leaving the game.

**To Reproduce**
1. put stuff in furnace
2. leave world
3.rejoin
4. check furnace

It supposed to keep your stuff in there

**Versions**
- **Iron Furnaces**-1.18.1-3.1.0.
- **Forge**: 39.0.5
- **Fabric**: x.x.x

<details>
  <summary>Crashlog</summary>
  
  ```
  Log goes here
  ```

**Comment by xandertreat** [comment]
Yep. Getting exact same issue. Also seems to happen when you switch dimensions.

**Comment by AmbnG** [comment]
Same here and the only way that i know to fix this issue is to get the items inside the furnace before leaving

**Comment by Erabior** [comment]
can confirm this is happening to me on my dedicated server

**Comment by Zedrimar** [comment]
Can confirm. I am pretty sure this is because of how forge changed how NBT is stored with blocks. Even though I'm pretty sure there are no container blocks that store items or data on pickup, may be a good idea to check those too as those also are likely affected by the item/data deletion issue

**Comment by AmbnG** [comment]
Its fixed now
