### ISSUE TITLE
imponpatibility with project mmo mod

### ISSUE THREAD

**Issue by TheLynk** [Qelifern/IronFurnaces#82]
**Describe the bug**
incompatibility with the MMO mod project in 1.18.1 there are no smithing experience gains when cooking items 
I have already contacted the creator of the mmo mod project and he tells me that it is your side where the compatibility problem comes from 
**To Reproduce**
1. place the iron furnace
2. it time to smelt item
3. no gain xp smithing

**Expected behavior**
gain xp smithing to smelt item

**Versions**
- **Iron Furnaces**: 1.18.1-3.1.2
- **Forge**: 39.0.9
- **Project MMO**: 3.67.4

**Comment by Qelifern** [comment]
Fixed in latest version 3.1.4
