### ISSUE TITLE
[1.18.1] Iron Furnaces don't produce light like normal furnaces do

### ISSUE THREAD

**Issue by BugmanBugman** [Qelifern/IronFurnaces#83]
**Describe the bug**
Title
**To Reproduce**
1. Spawn any modded furnace
2. Smelt something
3. notice how its dark

**Expected behavior**
To produce light like normal furnaces

**Versions**
- **Iron Furnaces**: 3.1.3.
- **Forge** 39.0.9
- **Fabric**: x.x.x

![2022-01-01_17 37 38](https://user-images.githubusercontent.com/40730042/147862344-747971d0-de29-45be-bf7e-d20b8aadce7e.png)
![2022-01-01_17 37 27](https://user-images.githubusercontent.com/40730042/147862345-e26acd66-180a-4032-bb90-f25af1e2fcee.png)

**Comment by Wilyicaro** [comment]
You are probably using optifine, which for some reason "disables" the lit blockstate forge block lights

**Comment by Qelifern** [comment]
Cant reproduce this bug.

**Comment by Wilyicaro** [comment]
> Cant reproduce this bug.
I've known this bug for a while, you have to use optifine for the lighting not to work in the furnaces
