### ISSUE TITLE
[1.16.5] Can't open furnace with empty hand

### ISSUE THREAD

**Issue by ZEkA10000** [Qelifern/IronFurnaces#84]
**Describe the bug**
I can't open furnace without item in hand

**To Reproduce**
1. Modify furnace to Iron and higher 
2. Click on it
- **Video**
https://user-images.githubusercontent.com/25690631/148804786-e04e8f4c-730c-4e46-bf0e-a820fdc18862.mp4

**Expected behavior**
Showing GUI of furnace

**Versions**
- **Iron Furnaces**: [1.16.5] 2.7.7
- **Forge**: 36.2.22
- **Fabric**: -

**Comment by Qelifern** [comment]
1.16.5 is no longer supported
