### ISSUE TITLE
Furnaces not auto push items into storage drawers

### ISSUE THREAD

**Issue by MajorDeew** [Qelifern/IronFurnaces#85]
**Describe the bug**
Furnaces cannot auto push cooked items to 1x1 storage drawers

**To Reproduce**
1. Put storage drawer on a side of a furnace
2. Put fuel and items to cook
3. Set output the side of the furnace where the drawer is located
4. Enable auto output on furnace

GIF
    https://multicraft.majordevelop.it/ezgif-3-670686ec6e.gif
    
**Expected behavior**
Cooked items pushed to storage drawers

**Versions**
- **Iron Furnaces**: [1.16.5] 2.7.7
- **Forge**: 36.2.20
- **Fabric**: -

**Comment by bobthebigbat** [comment]
I've got the same problem playing Cuboid Outpost. I've tried the same setup on the back wall visible in the gif but that isn't working for me. I've tried outputting to compacting drawers with the same issue.
Pulling from storage drawers seems fine, but can't auto output to them.

**Comment by bobthebigbat** [comment]
So according to the changelog (https://github.com/Qelifern/IronFurnaces/blob/1.16.5/ifchangelog.txt) - "Items can no longer be automaticly outputed to an adjacent storage drawer which fixes an issue where that item might end up being deleted".
That change was made in version 2.6.5.
Curious how other mods/machines deal with the issue. Maybe someone can eventually fix it, or we can have a modified version with the change in 2.6.5 reversed (or an option in config to enable/disable output to storage drawers) with a warning.

**Comment by MajorDeew** [comment]
I am seeing the commit where author disable the auto output function to storage drawer, but i'm not good in programming mod for minecraft.
Maybe you could download the code in the previous commint, built into a jar an then upload to you minecraft dir.

**Comment by aetasoul** [comment]
Hi,
Any update on this?

**Comment by Qelifern** [comment]
This is intended behavior, might look into how storage drawers are set up.
