### ISSUE TITLE
[1.18.1] quitting world deletes contents from any level furnace

### ISSUE THREAD

**Issue by ExiledMiner04** [Qelifern/IronFurnaces#86]
**Describe the bug**
I put in materials to be smelted into a gold furnace and I saved and quit to troubleshoot unrelated things. I come back to find my materials and my fuel are gone nowhere to be found.

**To Reproduce**
1. Put fuel and smeltable items
2. Save and quit
3. return to world

**Expected behavior**
The furnace to pick up from where it began like vanilla furnaces.

**Versions**
- **Iron Furnaces**: 1.18.1-3.1.3
- **Forge**: 39.0.20
- **Fabric**: x.x.x

<details>
  <summary>Crashlog</summary>
  
  ```
  Log goes here
  ```

**Comment by Qelifern** [comment]
Cant reproduce this bug.
