### ISSUE TITLE
Cannot craft any furnace higher than gold

### ISSUE THREAD

**Issue by sebbybby** [Qelifern/IronFurnaces#87]
**Describe the bug**
I cannot craft furnaces higher than gold. Everything up to, and including gold works just fine. 

**To Reproduce**
1. place correct items in crafting table for diamond, crystal, emerald, obsidian, and netherite furnaces
2.
3.

**Expected behavior**
I expect the corresponding furnace to appear in the crafting table when the correct recipe is placed in the table, but this is only the case for furnaces up to gold
**Versions**
- **Iron Furnaces**: 1.18-1.3.1.4
- **Forge**: 39.0.64
- **Fabric**: 0.46.1 1.18
![unknown](https://user-images.githubusercontent.com/99144539/152700049-8e39c6d6-fc59-4833-bda2-09b38e2c1726.png)
![unknown](https://user-images.githubusercontent.com/99144539/152700080-807566da-7675-42c7-ac55-6e6385243ef8.png)
![unknown](https://user-images.githubusercontent.com/99144539/152700083-d0801cb8-ede6-4e85-93f2-5344cd973e4e.png)
![unknown](https://user-images.githubusercontent.com/99144539/152700091-162a73a0-060a-4a02-a15d-4aaf56bf6d23.png)

<details>
  <summary>Crashlog</summary>
  

  ```
  Log goes here


  ```

**Comment by XenoMustache** [comment]
So are you using Fabric or Forge?

**Comment by Qelifern** [comment]
Unable to reproduce issue
