### ISSUE TITLE
Wireless Heater loses energy after saving / reloading the saves the energy

### ISSUE THREAD

**Issue by gamenTV** [Qelifern/IronFurnaces#91]
**Describe the bug**
Wireless Heater loses energy after saving / reloading the saves the energy

**To Reproduce**
1. Create World
2. Place Wireless Heater
3. give the Wireless Heater some energy
4. Save
5. Rejoin

**Versions**
- **Iron Furnaces**: 1.18.1-3.1.4
- **Forge**: 39.0.88

**Comment by Qelifern** [comment]
Fixed since 3.3.0
