### ISSUE TITLE
Update checker uses wrong url in 1.18.1 3.1.4 

### ISSUE THREAD

**Issue by pavog** [Qelifern/IronFurnaces#94]
### Forge Version

1.18.1

### Iron Furnaces Version

3.1.4

### Describe your issue

The latest version of iron furnances (ironfurnaces-1.18.1-3.1.4.jar) from [curseforge](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces) / [download](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces/files/3635717) points to the wrong github branch for the update checker.

It requests the updateVersions.properties file from https://raw.githubusercontent.com/Qelifern/118IronFurnaces/main/update/updateVersions.properties.
But there is no branch named "main".

I suggest changing the name of the master branch to main or releasing a new version on Curseforge.

### Crash Report

https://mclo.gs/lCD9oFx

**Comment by Qelifern** [comment]
fixed with 3.2.0
