### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by BugmanBugman** [Qelifern/IronFurnaces#98]
### Forge Version

36.1.20

### Iron Furnaces Version

3.3.0

### Describe your issue

Server crashes when starting up on latest server

### Crash Report

https://gist.github.com/BugmanBugman/c4a9fcb6de6541c140005e66684b91db

**Comment by Zedrimar** [comment]
Can confirm. I get a different crash report however. 

Crash: https://pastebin.com/CmhrE3P5

Seems to only affect furnaces already placed in the world prior to update. I tested with a brand new world (same mod set) and new furnaces are not affected. I have found an odd work around though. Make backups before doing this though in case something goes wrong.

Work around: remove mod, reload world. Exit the world, then reload the game with the iron furnaces mod added back in and everything should still be there. Just break and replace the furnaces you had before and everything should go back to normal. I saved it and reloaded the world and it didn't crash after coming back, so it seemed to work.

**Comment by erasels** [comment]
Can confirm, same thing happens to me (MC 1.18.2, forge 40.1.xx)
https://pastebin.com/2QhAFfNs

I tried downgrading to a previous version, mining all my iron furnaces, and updating however the same crash occurred when I tried placing one of the furnaces again once updated.

**Comment by lays24mc** [comment]
> 

Thanks. Works fine for me :D

**Comment by lays24mc** [comment]
> Can confirm. I get a different crash report however.
> 
> Crash: https://pastebin.com/CmhrE3P5
> 
> Seems to only affect furnaces already placed in the world prior to update. I tested with a brand new world (same mod set) and new furnaces are not affected. I have found an odd work around though. Make backups before doing this though in case something goes wrong.
> 
> Work around: remove mod, reload world. Exit the world, then reload the game with the iron furnaces mod added back in and everything should still be there. Just break and replace the furnaces you had before and everything should go back to normal. I saved it and reloaded the world and it didn't crash after coming back, so it seemed to work.

Thanks, works fine for me. Looks like Refinded Storage doesn't like the new UI or slot distribution of the furnances

**Comment by Cntrldfusion** [comment]
> Can confirm. I get a different crash report however.
> 
> Crash: https://pastebin.com/CmhrE3P5
> 
> Seems to only affect furnaces already placed in the world prior to update. I tested with a brand new world (same mod set) and new furnaces are not affected. I have found an odd work around though. Make backups before doing this though in case something goes wrong.
> 
> Work around: remove mod, reload world. Exit the world, then reload the game with the iron furnaces mod added back in and everything should still be there. Just break and replace the furnaces you had before and everything should go back to normal. I saved it and reloaded the world and it didn't crash after coming back, so it seemed to work.

Had the same crash after upgrading my server to ATM7 0.4.0.  Followed this work around it resolved the crash.  SO it does seem to be related to worlds where iron furnaces are placed prior to updating to the latest version.

**Comment by grimgrinninjay** [comment]
> > Can confirm. I get a different crash report however.
> > Crash: https://pastebin.com/CmhrE3P5
> > Seems to only affect furnaces already placed in the world prior to update. I tested with a brand new world (same mod set) and new furnaces are not affected. I have found an odd work around though. Make backups before doing this though in case something goes wrong.
> > Work around: remove mod, reload world. Exit the world, then reload the game with the iron furnaces mod added back in and everything should still be there. Just break and replace the furnaces you had before and everything should go back to normal. I saved it and reloaded the world and it didn't crash after coming back, so it seemed to work.
> 
> Had the same crash after upgrading my server to ATM7 0.4.0. Followed this work around it resolved the crash. SO it does seem to be related to worlds where iron furnaces are placed prior to updating to the latest version.

Same crash. Work around fixed it for us as well.

**Comment by Gbergz** [comment]
Can confirm this crash as OP posted.

Workaround works to an extent.
Looking forward to an official fix. 👍
