### ISSUE TITLE
NoClassDefFoundError BlockIronFurnaceTileBase loading world after upgrade 

### ISSUE THREAD

**Issue by leagris** [Qelifern/IronFurnaces#99]
### Forge Version

40.1.20

### Iron Furnaces Version

1.18.2-3.3.0

### Describe your issue

Crash on loading a world that has been created with older version 1.8.2.3.2.1

Downgrading IronFurnace the world loads again without crash.

### Crash Report

https://gist.github.com/leagris/2d0ce2e2f37f49700b6f39c2d6367709

**Comment by Qelifern** [comment]
Load the world without Iron Furances installed once then re-add it and it should work.
